# Generated by Django 4.2.17 on 2026-02-17 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('OPERATOR', 'Operator')], default='OPERATOR', max_length=15)),
                ('name', models.CharField(help_text='Display name, e.g. "Academic Operator"', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_manage_students', models.BooleanField(default=True)),
                ('can_manage_teachers', models.BooleanField(default=True)),
                ('can_manage_exams', models.BooleanField(default=False)),
                ('can_manage_attendance', models.BooleanField(default=True)),
                ('can_manage_content', models.BooleanField(default=False)),
                ('can_manage_finance', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_manage_integrations', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('can_manage_roles', models.BooleanField(default=False)),
                ('can_view_audit', models.BooleanField(default=True)),
                ('can_manage_website', models.BooleanField(default=False)),
                ('can_manage_ai', models.BooleanField(default=False)),
                ('allowed_centers', models.JSONField(blank=True, default=list, help_text='Restrict to specific center IDs')),
                ('allowed_batches', models.JSONField(blank=True, default=list, help_text='Restrict to specific batch IDs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'staff_roles',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='staff_role',
            field=models.ForeignKey(blank=True, help_text='Staff panel access role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_admins', to='accounts.staffrole'),
        ),
    ]
