# Generated by Django 4.2.17 on 2026-02-18 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('accounts', '0002_staffrole_admin_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_type',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TENANT_ADMIN', 'Tenant Admin'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('BRANCH_ADMIN', 'Branch Admin'), ('ACADEMIC_ADMIN', 'Academic Admin'), ('FINANCE_ADMIN', 'Finance Admin'), ('SUPPORT_ADMIN', 'Support Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='applies_to',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('TEACHING_ASSISTANT', 'Teaching Assistant'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('ALL', 'All')], default='ALL', max_length=20),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_type', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=50)),
                ('resource', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=5)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, help_text='Snapshot of evaluated attributes', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant_id', 'user_id', 'timestamp'], name='idx_access_user_ts'), models.Index(fields=['tenant_id', 'action', 'resource'], name='idx_access_action')],
            },
        ),
        migrations.CreateModel(
            name='ABACPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="e.g. 'enrollment_active_only'", max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource', models.CharField(help_text="e.g. 'COURSE', 'GRADE', 'USER'", max_length=50)),
                ('action', models.CharField(help_text="e.g. 'VIEW', 'EDIT', 'DELETE'", max_length=20)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON condition tree. Example: {"all": [{"attr": "user.status", "op": "eq", "value": "ACTIVE"}, {"attr": "enrollment.status", "op": "in", "value": ["ENROLLED","ACTIVE"]}]}')),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], default='ALLOW', max_length=5)),
                ('priority', models.IntegerField(default=0, help_text='Higher = evaluated first. Deny wins on tie.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abac_policies', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ABAC Policy',
                'verbose_name_plural': 'ABAC Policies',
                'db_table': 'abac_policies',
                'ordering': ['-priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin'), ('PARENT', 'Parent')], max_length=10)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('TENANT', 'Tenant'), ('DEPARTMENT', 'Department'), ('COURSE', 'Course'), ('BATCH', 'Batch')], default='TENANT', max_length=15)),
                ('scope_id', models.UUIDField(blank=True, help_text='ID of the scoped entity (department, course, batch). Null for GLOBAL/TENANT.', null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'user_role_assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'user_id', 'user_type'], name='idx_ura_user'), models.Index(fields=['tenant', 'role'], name='idx_ura_role'), models.Index(fields=['scope_type', 'scope_id'], name='idx_ura_scope')],
            },
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'user_id', 'user_type', 'role', 'scope_type', 'scope_id'), name='uq_user_role_scope'),
        ),
    ]
