# Generated by Django 4.2.17 on 2026-02-13 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopperStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('photo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('exam_name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('testimonial', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'topper_students',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_code', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('material_type', models.CharField(choices=[('EBOOK', 'E-Book / PDF'), ('VIDEO', 'Video'), ('QUESTION_PAPER', 'Question Paper'), ('NOTES', 'Notes'), ('ASSIGNMENT', 'Assignment'), ('REFERENCE', 'Reference Material'), ('SOLUTION', 'Solution'), ('TRAINING_VIDEO', 'Training Video'), ('PRESENTATION', 'Presentation')], default='EBOOK', max_length=20)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('video_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('video_embed_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('video_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('target_audience', models.CharField(choices=[('STUDENT', 'Students'), ('TEACHER', 'Teachers'), ('ALL', 'All')], default='STUDENT', max_length=10)),
                ('difficulty_level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=15, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('requires_enrollment', models.BooleanField(default=True)),
                ('allowed_batches', models.JSONField(blank=True, default=list)),
                ('uploaded_by_id', models.UUIDField(blank=True, null=True)),
                ('uploaded_by_type', models.CharField(blank=True, max_length=10, null=True)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=200, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_meta', models.JSONField(blank=True, null=True)),
                ('ext_material_1', models.CharField(blank=True, max_length=500, null=True)),
                ('ext_material_2', models.CharField(blank=True, max_length=500, null=True)),
                ('ext_material_3', models.JSONField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.batch')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.chapter')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='tenants.tenant')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.topic')),
            ],
            options={
                'db_table': 'study_materials',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('apply_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('documents_required', models.JSONField(blank=True, default=list)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='tenants.tenant')),
            ],
            options={
                'db_table': 'scholarships',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='tenants.tenant')),
            ],
            options={
                'db_table': 'photo_gallery',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('user_type', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('BOOKMARK', 'Bookmarked')], max_length=10)),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('progress_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='materials.studymaterial')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'material_accesses',
            },
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['tenant', 'material_type'], name='idx_material_type'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['tenant', 'subject'], name='idx_material_subject'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['tenant', 'is_published'], name='idx_material_published'),
        ),
        migrations.AddIndex(
            model_name='materialaccess',
            index=models.Index(fields=['tenant', 'material', 'user_id'], name='idx_maccess_material_user'),
        ),
    ]
