# Generated by Django 4.2.17 on 2026-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialaccess',
            options={'verbose_name_plural': 'Material accesses'},
        ),
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ['category', 'sort_order'], 'verbose_name_plural': 'Photo galleries'},
        ),
    ]
