# Generated by Django 4.2.17 on 2026-02-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_batches', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='batchteacher',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='batchstudent',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_students', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='batchstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_batches', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='batchstudent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='batch',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='academics.group'),
        ),
        migrations.AddField(
            model_name='batch',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='batch',
            name='teachers',
            field=models.ManyToManyField(related_name='teaching_batches', through='academics.BatchTeacher', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='batch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['tenant', 'chapter'], name='idx_topic_chapter'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['tenant', 'name'], name='idx_subject_name'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['tenant', 'name'], name='idx_group_name'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['tenant', 'subject'], name='idx_chapter_subject'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'name'], name='idx_category_name'),
        ),
        migrations.AlterUniqueTogether(
            name='batchteacher',
            unique_together={('batch', 'teacher', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='batchstudent',
            unique_together={('batch', 'student')},
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['tenant', 'status'], name='idx_batch_status'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['tenant', 'exam_target'], name='idx_batch_exam'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_batch_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('tenant', 'session_name'), name='uq_session_name_per_tenant'),
        ),
    ]
