# Generated by Django 4.2.17 on 2026-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinetestmarks',
            options={'verbose_name_plural': 'Offline test marks'},
        ),
    ]
