"""
Migration Health Tests — Auto-generated by remediation script

These tests verify that the migration state is clean.
Run before and after every Django upgrade.

Usage: python manage.py test apps.tests.test_migrations
"""

from django.test import TestCase
from django.core.management import call_command
from io import StringIO


class MigrationHealthTests(TestCase):
    """Test that migrations are in a healthy state."""

    def test_no_pending_migrations(self):
        """All migrations should be applied."""
        try:
            call_command('migrate', '--check', stdout=StringIO(), stderr=StringIO())
        except SystemExit as e:
            if e.code != 0:
                self.fail(
                    "There are unapplied migrations. Run: python manage.py migrate"
                )

    def test_no_migration_conflicts(self):
        """No migration conflicts should exist."""
        out = StringIO()
        try:
            call_command('showmigrations', '--plan', stdout=out, stderr=StringIO())
        except Exception as e:
            self.fail(f"Migration plan failed: {e}")

    def test_models_match_migrations(self):
        """Models should not have unmigrated changes."""
        out = StringIO()
        try:
            call_command('makemigrations', '--check', '--dry-run',
                        stdout=out, stderr=StringIO())
        except SystemExit as e:
            if e.code != 0:
                self.fail(
                    "Model changes detected without migrations. "
                    "Run: python manage.py makemigrations"
                )
