"""
Settings Verification Tests — Auto-generated by remediation script

These tests verify critical Django settings are configured correctly.
Run after every settings change or Django upgrade.

Usage: python manage.py test apps.tests.test_settings
"""

from django.test import TestCase
from django.conf import settings


class SecuritySettingsTests(TestCase):
    """Test that security-critical settings are properly configured."""

    def test_secret_key_not_default(self):
        """SECRET_KEY should not be the Django default."""
        self.assertNotEqual(
            settings.SECRET_KEY,
            'django-insecure-change-me',
            "SECRET_KEY is still the default — change it!"
        )
        self.assertGreater(len(settings.SECRET_KEY), 20,
            "SECRET_KEY is too short")

    def test_drf_default_permissions(self):
        """DRF should default to IsAuthenticated, not AllowAny."""
        drf_settings = getattr(settings, 'REST_FRAMEWORK', {})
        perm_classes = drf_settings.get('DEFAULT_PERMISSION_CLASSES', [])
        for perm in perm_classes:
            self.assertNotIn('AllowAny', perm,
                "DRF defaults to AllowAny — this is a security risk!")

    def test_drf_authentication_configured(self):
        """DRF should have authentication classes configured."""
        drf_settings = getattr(settings, 'REST_FRAMEWORK', {})
        auth_classes = drf_settings.get('DEFAULT_AUTHENTICATION_CLASSES', [])
        self.assertGreater(len(auth_classes), 0,
            "No DRF authentication classes configured!")

    def test_debug_off_in_production(self):
        """DEBUG should be False in production settings."""
        # This test only makes sense in production
        if 'production' in str(getattr(settings, 'SETTINGS_MODULE', '')).lower():
            self.assertFalse(settings.DEBUG,
                "DEBUG is True in production settings!")

    def test_database_configured(self):
        """Database should be configured."""
        db = settings.DATABASES.get('default', {})
        self.assertIn(db.get('ENGINE', ''), [
            'django.db.backends.postgresql',
            'django.db.backends.postgresql_psycopg2',
        ], "Expected PostgreSQL database backend")
