"""
Model Tests — Auto-generated by remediation script

These tests verify that all models can be imported and
their basic metadata is correct.

Usage: python manage.py test apps.tests.test_models
"""

from django.test import TestCase
from django.apps import apps
from django.db import connection


class ModelImportTests(TestCase):
    """Test that all models can be imported and have valid metadata."""

    def test_all_models_importable(self):
        """Every registered model should be importable."""
        models = apps.get_models()
        self.assertGreater(len(models), 0, "No models found!")

    def test_all_models_have_str(self):
        """Models should have __str__ for admin display."""
        for model in apps.get_models():
            # Just verify __str__ exists and is callable
            self.assertTrue(
                hasattr(model, "__str__"),
                f"{model.__name__} missing __str__"
            )

    def test_all_models_have_meta(self):
        """Models should have valid Meta configuration."""
        for model in apps.get_models():
            meta = model._meta
            self.assertIsNotNone(meta.app_label,
                f"{model.__name__} missing app_label")
            self.assertIsNotNone(meta.db_table,
                f"{model.__name__} missing db_table")


class ModelTableTests(TestCase):
    """Test that model tables exist in the database."""

    def test_all_tables_exist(self):
        """Every model's DB table should exist."""
        existing_tables = set(connection.introspection.table_names())
        missing = []
        for model in apps.get_models():
            if not model._meta.managed:
                continue  # Skip unmanaged models
            if model._meta.db_table not in existing_tables:
                missing.append(
                    f"{model._meta.app_label}.{model.__name__} -> {model._meta.db_table}"
                )
        if missing:
            self.fail(
                f"Missing tables (run migrate?): {missing}"
            )

