# Generated by Django 4.2.17 on 2026-02-13 17:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Unique tenant code e.g. 'INST001'", max_length=50, unique=True)),
                ('name', models.CharField(help_text="e.g. 'ABC Coaching Institute'", max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=500, null=True)),
                ('subdomain', models.CharField(help_text="Subdomain prefix e.g. 'abc' for abc.platform.com", max_length=100, unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text="Custom domain e.g. 'www.abccoaching.com'", max_length=255, null=True, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('favicon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('primary_color', models.CharField(default='#1E3A5F', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True)),
                ('theme_config', models.JSONField(blank=True, default=dict)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('youtube_channel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_client_id', models.TextField(blank=True, help_text='Encrypted', null=True)),
                ('youtube_client_secret', models.TextField(blank=True, help_text='Encrypted', null=True)),
                ('youtube_refresh_token', models.TextField(blank=True, help_text='Encrypted', null=True)),
                ('youtube_quota_limit', models.IntegerField(default=10000)),
                ('youtube_quota_used', models.IntegerField(default=0)),
                ('youtube_quota_reset_at', models.DateTimeField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise'), ('CUSTOM', 'Custom')], default='STARTER', max_length=20)),
                ('max_students', models.IntegerField(default=100)),
                ('max_teachers', models.IntegerField(default=10)),
                ('max_storage_gb', models.IntegerField(default=50)),
                ('features_enabled', models.JSONField(blank=True, default=dict, help_text='Feature flags per tenant')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TRIAL', 'Trial'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('date_format', models.CharField(blank=True, default='DD/MM/YYYY', max_length=20, null=True)),
                ('academic_year_start', models.IntegerField(default=4, help_text='Month 1-12')),
                ('data_retention_days', models.IntegerField(default=365)),
                ('gdpr_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('config_1', models.CharField(blank=True, max_length=500, null=True)),
                ('config_2', models.CharField(blank=True, max_length=500, null=True)),
                ('config_3', models.TextField(blank=True, null=True)),
                ('config_4', models.JSONField(blank=True, null=True)),
                ('config_5', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['subdomain'], name='idx_tenant_subdomain'), models.Index(fields=['custom_domain'], name='idx_tenant_custom_domain'), models.Index(fields=['status'], name='idx_tenant_status')],
            },
        ),
    ]
