# Generated by Django 4.2.17 on 2026-02-13 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_type', models.CharField(max_length=10)),
                ('device_fingerprint', models.CharField(max_length=500, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('DESKTOP', 'Desktop'), ('LAPTOP', 'Laptop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('os_name', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('push_token', models.TextField(blank=True, null=True)),
                ('push_platform', models.CharField(blank=True, max_length=20, null=True)),
                ('device_meta', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tenants.tenant')),
            ],
            options={
                'db_table': 'user_devices',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_type', models.CharField(max_length=10)),
                ('session_token', models.CharField(db_index=True, max_length=500, unique=True)),
                ('refresh_token_hash', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('geo_city', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_state', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_country', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('LOGGED_OUT', 'Logged Out'), ('REVOKED', 'Revoked'), ('FORCE_TERMINATED', 'Force Terminated')], default='ACTIVE', max_length=20)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('total_active_seconds', models.IntegerField(default=0)),
                ('concurrent_session_check', models.BooleanField(default=True)),
                ('is_primary_session', models.BooleanField(default=True)),
                ('session_meta', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions_tracking.userdevice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('user_type', models.CharField(max_length=10)),
                ('activity_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('CLASS_JOIN', 'Class Join'), ('CLASS_LEAVE', 'Class Leave'), ('TEST_START', 'Test Start'), ('TEST_SUBMIT', 'Test Submit'), ('MATERIAL_VIEW', 'Material View'), ('MATERIAL_DOWNLOAD', 'Material Download'), ('PROFILE_UPDATE', 'Profile Update'), ('SETTINGS_CHANGE', 'Settings Change'), ('MESSAGE_SENT', 'Message Sent'), ('TICKET_CREATED', 'Ticket Created'), ('CUSTOM', 'Custom')], max_length=25)),
                ('activity_description', models.CharField(blank=True, max_length=500, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=500, null=True)),
                ('page_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('referrer_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('activity_data', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions_tracking.usersession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='tenants.tenant')),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=10, null=True)),
                ('username_attempted', models.CharField(max_length=200)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('MFA_REQUIRED', 'MFA Required'), ('MFA_FAILED', 'MFA Failed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('INACTIVE', 'Inactive Account')], max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('geo_city', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_country', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions_tracking.userdevice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='tenants.tenant')),
            ],
            options={
                'db_table': 'login_history',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['tenant', 'user_id', 'status'], name='idx_session_user_status'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_token'], name='idx_session_token'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['tenant', 'status', 'expires_at'], name='idx_session_expiry'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['tenant', 'user_id', 'user_type'], name='idx_device_user'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['tenant', 'user_id', 'occurred_at'], name='idx_activity_user_time'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['tenant', 'activity_type'], name='idx_activity_type'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['tenant', 'user_id', 'attempted_at'], name='idx_login_user_time'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['tenant', 'ip_address'], name='idx_login_ip'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['tenant', 'result'], name='idx_login_result'),
        ),
    ]
