# Generated by Django 4.2.17 on 2026-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-attempted_at'], 'verbose_name_plural': 'Login history'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-occurred_at'], 'verbose_name_plural': 'User activities'},
        ),
    ]
