# Generated by Django 4.2.17 on 2026-02-13 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('content_html', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('announcement_type', models.CharField(choices=[('GENERAL', 'General'), ('ACADEMIC', 'Academic'), ('EXAM', 'Exam'), ('EVENT', 'Event'), ('MAINTENANCE', 'Maintenance'), ('URGENT', 'Urgent')], default='GENERAL', max_length=15)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'Students Only'), ('TEACHERS', 'Teachers Only'), ('BATCH', 'Specific Batch'), ('CUSTOM', 'Custom')], default='ALL', max_length=10)),
                ('target_batches', models.JSONField(blank=True, default=list)),
                ('target_user_ids', models.JSONField(blank=True, default=list)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField()),
                ('created_by_type', models.CharField(max_length=10)),
                ('created_by_name', models.CharField(blank=True, max_length=200, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('view_count', models.IntegerField(default=0)),
                ('acknowledgement_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tenants.tenant')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical Issue'), ('ACCOUNT', 'Account Related'), ('PAYMENT', 'Payment Issue'), ('CONTENT', 'Content Query'), ('EXAM', 'Exam Related'), ('GENERAL', 'General'), ('FEEDBACK', 'Feedback')], default='GENERAL', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting on User'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], default='OPEN', max_length=15)),
                ('submitted_by_id', models.UUIDField()),
                ('submitted_by_type', models.CharField(max_length=10)),
                ('submitted_by_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submitted_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned_to_id', models.UUIDField(blank=True, null=True)),
                ('assigned_to_type', models.CharField(blank=True, max_length=10, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.UUIDField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('ticket_meta', models.JSONField(blank=True, null=True)),
                ('ext_ticket_1', models.CharField(blank=True, max_length=500, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'support_tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.UUIDField()),
                ('sender_type', models.CharField(max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_internal_note', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.supportticket')),
            ],
            options={
                'db_table': 'ticket_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('user_type', models.CharField(max_length=10)),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('ACTION_REQUIRED', 'Action Required')], default='INFO', max_length=20)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('WHATSAPP', 'WhatsApp')], default='IN_APP', max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('action_data', models.JSONField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.tenant')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.UUIDField()),
                ('sender_type', models.CharField(max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_id', models.UUIDField()),
                ('recipient_type', models.CharField(max_length=10)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('thread_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted_by_sender', models.BooleanField(default=False)),
                ('is_deleted_by_recipient', models.BooleanField(default=False)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communication.directmessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='tenants.tenant')),
            ],
            options={
                'db_table': 'direct_messages',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('user_type', models.CharField(max_length=10)),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='communication.announcement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'announcement_reads',
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant', 'status'], name='idx_ticket_status'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant', 'submitted_by_id'], name='idx_ticket_submitter'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'user_id', 'is_read'], name='idx_notif_user_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'user_id', 'channel'], name='idx_notif_user_channel'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['tenant', 'recipient_id', 'is_read'], name='idx_dm_recipient'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['tenant', 'sender_id'], name='idx_dm_sender'),
        ),
        migrations.AddConstraint(
            model_name='announcementread',
            constraint=models.UniqueConstraint(fields=('announcement', 'user_id'), name='uq_announcement_read'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['tenant', 'is_published', 'target_audience'], name='idx_announcement_audience'),
        ),
    ]
