# Generated by Django 4.2.17 on 2026-02-13 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('tenants', '0001_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=10)),
                ('user_id', models.UUIDField(db_index=True)),
                ('attendance_date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('EXCUSED', 'Excused')], default='ABSENT', max_length=10)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('LIVE_CLASS', 'Live Class Auto'), ('BIOMETRIC', 'Biometric'), ('QR_CODE', 'QR Code'), ('GEOFENCE', 'Geofence'), ('SYSTEM', 'System Generated')], default='MANUAL', max_length=15)),
                ('source_reference_id', models.UUIDField(blank=True, help_text='Link to ScheduledClass or session', null=True)),
                ('watch_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('watch_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('marked_by', models.UUIDField(blank=True, null=True)),
                ('marked_by_type', models.CharField(blank=True, max_length=10, null=True)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_corrected', models.BooleanField(default=False)),
                ('original_status', models.CharField(blank=True, max_length=10, null=True)),
                ('corrected_by', models.UUIDField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.TextField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('attendance_meta', models.JSONField(blank=True, null=True)),
                ('ext_att_1', models.CharField(blank=True, max_length=500, null=True)),
                ('ext_att_2', models.JSONField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.batch')),
                ('live_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='classes.scheduledclass')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=10)),
                ('user_id', models.UUIDField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_working_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('half_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('holiday_days', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.batch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'attendance_summaries',
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by', models.UUIDField()),
                ('requested_by_type', models.CharField(max_length=10)),
                ('requested_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('EXCUSED', 'Excused')], max_length=10)),
                ('reason', models.TextField()),
                ('supporting_document', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='attendance.attendance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'attendance_correction_requests',
            },
        ),
        migrations.AddConstraint(
            model_name='attendancesummary',
            constraint=models.UniqueConstraint(fields=('tenant', 'user_type', 'user_id', 'month', 'year'), name='uq_attendance_summary_monthly'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['tenant', 'user_type', 'user_id', 'attendance_date'], name='idx_att_user_date'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['tenant', 'attendance_date', 'status'], name='idx_att_date_status'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['tenant', 'batch', 'attendance_date'], name='idx_att_batch_date'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('tenant', 'user_type', 'user_id', 'attendance_date'), name='uq_attendance_per_user_per_day'),
        ),
    ]
