# Generated by Django 4.2.17 on 2026-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesummary',
            options={'verbose_name_plural': 'Attendance summaries'},
        ),
    ]
