# Generated by Django 4.2.17 on 2026-02-13 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('FULL', 'Full Maintenance'), ('PARTIAL', 'Partial (Read-Only)'), ('FEATURE', 'Feature Specific')], default='FULL', max_length=10)),
                ('affected_features', models.JSONField(blank=True, default=list)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'maintenance_windows',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_key', models.CharField(db_index=True, max_length=200)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('setting_json', models.JSONField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('DECIMAL', 'Decimal')], default='STRING', max_length=10)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = global setting', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='MFAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mfa_type', models.CharField(choices=[('TOTP', 'Time-based OTP'), ('SMS', 'SMS OTP'), ('EMAIL', 'Email OTP')], default='EMAIL', max_length=10)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('applies_to_user_types', models.JSONField(blank=True, default=list)),
                ('otp_length', models.IntegerField(default=6)),
                ('otp_expiry_seconds', models.IntegerField(default=300)),
                ('max_attempts', models.IntegerField(default=5)),
                ('lockout_duration_minutes', models.IntegerField(default=30)),
                ('resend_cooldown_seconds', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_policies', to='tenants.tenant')),
            ],
            options={
                'db_table': 'mfa_policies',
            },
        ),
        migrations.CreateModel(
            name='FounderInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_type', models.CharField(choices=[('FOUNDER', 'Founder'), ('MANAGEMENT', 'Management Team'), ('ADVISOR', 'Advisor')], default='FOUNDER', max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='tenants.tenant')),
            ],
            options={
                'db_table': 'founder_info',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_key', models.CharField(max_length=200)),
                ('flag_name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.IntegerField(default=0)),
                ('allowed_user_types', models.JSONField(blank=True, default=list)),
                ('allowed_user_ids', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='tenants.tenant')),
            ],
            options={
                'db_table': 'feature_flags',
            },
        ),
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField()),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('APP', 'Mobile App'), ('REFERRAL', 'Referral'), ('WALK_IN', 'Walk-in')], default='WEBSITE', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted'), ('CLOSED', 'Closed')], default='NEW', max_length=10)),
                ('assigned_to', models.UUIDField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'enquiry_forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.UniqueConstraint(fields=('tenant', 'setting_key'), name='uq_system_setting_key'),
        ),
        migrations.AddConstraint(
            model_name='featureflag',
            constraint=models.UniqueConstraint(fields=('tenant', 'flag_key'), name='uq_feature_flag_key'),
        ),
    ]
