# Generated by Django 4.2.17 on 2026-02-14 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLinkConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('YOUTUBE', 'YouTube Live'), ('ZOOM', 'Zoom'), ('GOOGLE_MEET', 'Google Meet'), ('MS_TEAMS', 'Microsoft Teams'), ('CUSTOM', 'Custom URL')], max_length=15)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('api_endpoint', models.URLField(blank=True, max_length=500, null=True)),
                ('api_key_reference', models.CharField(blank=True, help_text='Reference to SystemSetting key for the API key', max_length=200, null=True)),
                ('client_id', models.CharField(blank=True, max_length=300, null=True)),
                ('client_secret_reference', models.CharField(blank=True, help_text='Reference to SystemSetting key for client secret', max_length=200, null=True)),
                ('oauth_token_reference', models.CharField(blank=True, help_text='Reference to SystemSetting key for OAuth token', max_length=200, null=True)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('auto_generate_link', models.BooleanField(default=False)),
                ('generate_minutes_before', models.IntegerField(default=15, help_text='Minutes before class to auto-generate link')),
                ('default_duration_minutes', models.IntegerField(default=60)),
                ('auto_record', models.BooleanField(default=False)),
                ('auto_admit_participants', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_link_configs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Class Link Configuration',
                'verbose_name_plural': 'Class Link Configurations',
                'db_table': 'class_link_configs',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('applies_to', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ALL', 'All')], default='ALL', max_length=10)),
                ('class_start_grace_minutes', models.IntegerField(default=10, help_text='Minutes after class start to still mark Present')),
                ('late_threshold_minutes', models.IntegerField(default=15, help_text='Minutes after which student is marked Late')),
                ('absent_threshold_minutes', models.IntegerField(default=30, help_text='Minutes after which student is marked Absent')),
                ('min_watch_percentage', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum % of class to watch for Present status', max_digits=5)),
                ('auto_mark_from_live_class', models.BooleanField(default=True)),
                ('auto_mark_from_biometric', models.BooleanField(default=False)),
                ('auto_mark_from_geofence', models.BooleanField(default=False)),
                ('notify_absent_student', models.BooleanField(default=True)),
                ('notify_parent_on_absent', models.BooleanField(default=True)),
                ('notify_admin_below_threshold', models.BooleanField(default=True)),
                ('threshold_alert_percentage', models.DecimalField(decimal_places=2, default=75.0, help_text='Alert when attendance drops below this %', max_digits=5)),
                ('teacher_self_attendance_required', models.BooleanField(default=True, help_text='Teachers must mark their own attendance')),
                ('teacher_attendance_auto_from_class', models.BooleanField(default=True, help_text='Auto-mark teacher present when they start a class')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Attendance Rule',
                'verbose_name_plural': 'Attendance Rules',
                'db_table': 'attendance_rules',
                'ordering': ['rule_name'],
            },
        ),
        migrations.CreateModel(
            name='AIFeatureConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.CharField(db_index=True, help_text="Unique identifier, e.g. 'ai_summarization'", max_length=100)),
                ('feature_name', models.CharField(help_text='Display name', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('CONTENT', 'Content Generation'), ('ANALYTICS', 'Analytics & Prediction'), ('ASSESSMENT', 'Assessment Engine'), ('COMMUNICATION', 'Communication & Support'), ('AUTOMATION', 'Workflow Automation')], default='CONTENT', max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('integration_scope', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('ALL', 'All')], default='ALL', help_text='Which dashboard this feature appears on', max_length=10)),
                ('provider', models.CharField(blank=True, help_text="e.g. 'openai', 'google', 'internal'", max_length=100, null=True)),
                ('api_endpoint', models.URLField(blank=True, max_length=500, null=True)),
                ('api_key_reference', models.CharField(blank=True, help_text='Reference to SystemSetting key holding the API key', max_length=200, null=True)),
                ('max_requests_per_hour', models.IntegerField(default=100)),
                ('max_requests_per_user', models.IntegerField(default=20)),
                ('icon_class', models.CharField(default='fas fa-brain', help_text='Font Awesome icon class', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional configuration parameters')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = global setting', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_features', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'AI Feature',
                'verbose_name_plural': 'AI Features',
                'db_table': 'ai_feature_configs',
                'ordering': ['sort_order', 'feature_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='classlinkconfig',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform'), name='uq_class_link_platform_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='aifeatureconfig',
            constraint=models.UniqueConstraint(fields=('tenant', 'feature_key'), name='uq_ai_feature_key_per_tenant'),
        ),
    ]
