# Generated by Django 4.2.17 on 2026-02-17 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('system_config', '0002_classlinkconfig_attendancerule_aifeatureconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('LLM', 'LLM / AI Model'), ('YOUTUBE', 'YouTube Channel'), ('ZOOM', 'Zoom'), ('GOOGLE_MEET', 'Google Meet'), ('WHATSAPP', 'WhatsApp API'), ('SMS', 'SMS Gateway'), ('EMAIL', 'Email Service'), ('STORAGE', 'Cloud Storage'), ('PAYMENT', 'Payment Gateway'), ('ANALYTICS', 'Analytics Platform'), ('CUSTOM', 'Custom Integration')], max_length=20)),
                ('name', models.CharField(help_text='Display name e.g. "OpenAI GPT-4"', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(help_text='e.g. openai, anthropic, google, youtube', max_length=100)),
                ('api_endpoint', models.URLField(blank=True, max_length=500, null=True)),
                ('api_key', models.TextField(blank=True, help_text='Encrypted API key', null=True)),
                ('api_secret', models.TextField(blank=True, help_text='Encrypted secret', null=True)),
                ('oauth_client_id', models.CharField(blank=True, max_length=300, null=True)),
                ('oauth_client_secret', models.TextField(blank=True, null=True)),
                ('oauth_token', models.TextField(blank=True, null=True)),
                ('oauth_refresh_token', models.TextField(blank=True, null=True)),
                ('oauth_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('model_name', models.CharField(blank=True, help_text='e.g. gpt-4, claude-3', max_length=100, null=True)),
                ('max_tokens', models.IntegerField(blank=True, default=4096, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, default=0.7, max_digits=3, null=True)),
                ('system_prompt', models.TextField(blank=True, help_text='Default system prompt for AI', null=True)),
                ('channel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=200, null=True)),
                ('playlist_ids', models.JSONField(blank=True, default=list)),
                ('auto_sync_videos', models.BooleanField(default=False)),
                ('max_requests_per_hour', models.IntegerField(default=100)),
                ('max_requests_per_user', models.IntegerField(default=20)),
                ('daily_budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional params')),
                ('usage_stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'integration_configs',
                'ordering': ['integration_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('STUDENT', 'Student Report'), ('TEACHER', 'Teacher Report'), ('ATTENDANCE', 'Attendance Report'), ('EXAM', 'Exam/Test Report'), ('CENTER', 'Center-wise Report'), ('FINANCIAL', 'Financial Report'), ('COMBINED', 'Combined/Custom Report')], max_length=15)),
                ('filters_json', models.JSONField(blank=True, default=dict, help_text='Saved filter conditions')),
                ('columns_json', models.JSONField(blank=True, default=list, help_text='Selected columns for export')),
                ('group_by', models.JSONField(blank=True, default=list, help_text='Group by fields')),
                ('sort_by', models.JSONField(blank=True, default=list, help_text='Sort fields')),
                ('default_format', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF'), ('JSON', 'JSON')], default='EXCEL', max_length=5)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_cron', models.CharField(blank=True, max_length=100, null=True)),
                ('recipients_email', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('HERO', 'Hero Section'), ('ABOUT', 'About Section'), ('PROGRAMS', 'Programs Section'), ('TESTIMONIALS', 'Testimonials'), ('FOOTER', 'Footer'), ('SEO', 'SEO & Meta'), ('SOCIAL', 'Social Media Links'), ('BRANDING', 'Branding & Logo'), ('CONTACT', 'Contact Info'), ('CUSTOM', 'Custom Section')], max_length=20)),
                ('setting_key', models.CharField(max_length=200)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('setting_json', models.JSONField(blank=True, default=dict)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_settings',
                'ordering': ['section', 'sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='mfapolicy',
            options={'verbose_name_plural': 'MFA policies'},
        ),
        migrations.AddConstraint(
            model_name='websitesetting',
            constraint=models.UniqueConstraint(fields=('section', 'setting_key'), name='uq_website_section_key'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='tenants.tenant'),
        ),
    ]
