# Generated by Django 4.2.17 on 2026-02-18 21:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('system_config', '0003_integrationconfig_reporttemplate_websitesetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('news_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('NEWS', 'News'), ('EVENT', 'Event'), ('ALERT', 'Priority Alert'), ('UPDATE', 'Update')], default='NEWS', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('featured_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('show_as_banner', models.BooleanField(default=False)),
                ('banner_color', models.CharField(blank=True, default='#2563eb', max_length=20)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_news', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Website News',
                'verbose_name_plural': 'Website News',
                'db_table': 'website_news',
                'ordering': ['-priority', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=200)),
                ('author_type', models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('ALUMNI', 'Alumni'), ('OTHER', 'Other')], default='STUDENT', max_length=10)),
                ('author_designation', models.CharField(blank=True, help_text="e.g., 'Class 12 Student', 'JEE Advanced 2025'", max_length=200)),
                ('author_photo', models.URLField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(help_text='Testimonial text')),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('achievement', models.CharField(blank=True, help_text="e.g., 'AIR 45 in JEE Advanced'", max_length=300)),
                ('batch_year', models.CharField(blank=True, max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='tenants.tenant')),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['-is_featured', 'sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('QUICK_LINKS', 'Quick Links'), ('RESOURCES', 'Resources'), ('CONTACT', 'Contact Info'), ('SOCIAL', 'Social Media'), ('LEGAL', 'Legal Links'), ('NEWSLETTER', 'Newsletter'), ('CUSTOM', 'Custom Section')], max_length=20)),
                ('section_title', models.CharField(max_length=100)),
                ('links_json', models.JSONField(blank=True, default=list, help_text='Array of {label, url, icon?}')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_address', models.TextField(blank=True)),
                ('social_links_json', models.JSONField(blank=True, default=dict, help_text='{facebook, twitter, instagram, youtube, linkedin}')),
                ('newsletter_text', models.CharField(blank=True, max_length=200)),
                ('copyright_text', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'footer_configs',
                'ordering': ['sort_order'],
            },
        ),
    ]
