# Generated by Django 4.2.17 on 2026-02-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0004_add_website_news_testimonial_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='section',
            field=models.CharField(choices=[('HERO', 'Hero Section'), ('ABOUT', 'About Section'), ('PROGRAMS', 'Programs Section'), ('TESTIMONIALS', 'Testimonials'), ('FOUNDER', 'Founders & Team'), ('FOOTER', 'Footer'), ('SEO', 'SEO & Meta'), ('SOCIAL', 'Social Media Links'), ('BRANDING', 'Branding & Logo'), ('CONTACT', 'Contact Info'), ('NEWS', 'News & Updates'), ('CUSTOM', 'Custom Section')], max_length=20),
        ),
    ]
