# Generated by Django 4.2.17 on 2026-02-13 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=200, unique=True)),
                ('backup_type', models.CharField(choices=[('FULL', 'Full Backup'), ('INCREMENTAL', 'Incremental'), ('WAL_ARCHIVE', 'WAL Archive'), ('LOGICAL', 'Logical (pg_dump)')], default='FULL', max_length=15)),
                ('schedule_cron', models.CharField(default='0 2 * * *', max_length=100)),
                ('retention_days', models.IntegerField(default=30)),
                ('hot_backup_path', models.CharField(default='/backup/hot', max_length=500)),
                ('cold_backup_path', models.CharField(default='/backup/cold', max_length=500)),
                ('compression_enabled', models.BooleanField(default=True)),
                ('encryption_enabled', models.BooleanField(default=False)),
                ('encryption_key_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'backup_policies',
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='RUNNING', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('backup_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('backup_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tables_backed_up', models.IntegerField(blank=True, null=True)),
                ('rows_backed_up', models.BigIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='audit.backuppolicy')),
            ],
            options={
                'db_table': 'backup_history',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditPurgePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=100)),
                ('retention_days', models.IntegerField(default=365)),
                ('action_on_expiry', models.CharField(choices=[('DELETE', 'Delete'), ('ARCHIVE', 'Archive'), ('ANONYMIZE', 'Anonymize')], default='ARCHIVE', max_length=20)),
                ('archive_location', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_purge_at', models.DateTimeField(blank=True, null=True)),
                ('next_purge_at', models.DateTimeField(blank=True, null=True)),
                ('records_purged', models.BigIntegerField(default=0)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'audit_purge_policies',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('PERMISSION_CHANGE', 'Permission Change'), ('EXPORT', 'Data Export'), ('IMPORT', 'Data Import'), ('SETTINGS_CHANGE', 'Settings Change'), ('SYSTEM', 'System Event'), ('API_CALL', 'API Call')], max_length=20)),
                ('action_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=500, null=True)),
                ('http_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('is_security_event', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('audit_meta', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'action', 'created_at'], name='idx_audit_action_time'), models.Index(fields=['tenant', 'user_id'], name='idx_audit_user'), models.Index(fields=['tenant', 'resource_type', 'resource_id'], name='idx_audit_resource'), models.Index(fields=['tenant', 'is_security_event', 'created_at'], name='idx_audit_security')],
            },
        ),
    ]
