# Generated by Django 4.2.17 on 2026-02-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditpurgepolicy',
            options={'verbose_name_plural': 'Audit purge policies'},
        ),
        migrations.AlterModelOptions(
            name='backuphistory',
            options={'ordering': ['-started_at'], 'verbose_name_plural': 'Backup history'},
        ),
        migrations.AlterModelOptions(
            name='backuppolicy',
            options={'verbose_name_plural': 'Backup policies'},
        ),
    ]
