# Generated by Django 4.2.17 on 2026-02-13 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CLASS_STARTED', 'Class Started'), ('CLASS_ENDED', 'Class Ended'), ('TEST_PUBLISHED', 'Test Published'), ('TEST_RESULT', 'Test Result Available'), ('ANNOUNCEMENT', 'New Announcement'), ('NOTIFICATION', 'Notification'), ('ATTENDANCE_MARKED', 'Attendance Marked'), ('SESSION_TERMINATED', 'Session Terminated'), ('SYSTEM_ALERT', 'System Alert'), ('CHAT_MESSAGE', 'Chat Message'), ('CUSTOM', 'Custom Event')], max_length=25)),
                ('event_key', models.CharField(blank=True, max_length=200, null=True)),
                ('target_type', models.CharField(blank=True, help_text='USER, BATCH, TENANT, BROADCAST', max_length=20, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_channel', models.CharField(blank=True, max_length=500, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=5)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtime_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'realtime_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'event_type', 'is_delivered'], name='idx_rt_event_delivery'), models.Index(fields=['target_channel', 'is_delivered'], name='idx_rt_event_channel')],
            },
        ),
    ]
